;; Stuff for TNT 
(setq load-path (cons "/home/mfisher/tnt" load-path)) 
(load "tnt") 
(setq tnt-default-username "mfuXup") 
;(setq tnt-buggy-idle nil) 
(setq tnt-use-idle-timer nil) 
(setq tnt-email-to-pipe-to nil) 
(setq tnt-email-binary "/usr/bin/mail") 
(setq tnt-use-timestamps t) 
(setq tnt-beep-on-incoming-message 'audible) 
(setq tnt-beep-on-visible-incoming-message 'audible) 
(setq tnt-beep-on-chat-invitation 'audible) 
(setq tnt-beep-on-chat-message 'audible) 
(setq tnt-beep-on-visible-chat-message 'audible) 
(set-face-foreground 'tnt-my-name-face "red") 
